name: CI - Push a main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Mostrar mensaje
        run: echo "Workflow funcionando correctamente"
